{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out", "timestamp": "2024-10-14T05:42:12.552719+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out", "timestamp": "2024-10-14T05:42:16.543555+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-14T05:42:18.364809+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Authentication failed using Compute Engine authentication due to unavailable metadata server.", "timestamp": "2024-10-14T05:42:18.365613+00:00", "logger": "google.auth._default", "module": "_default", "function": "_get_gce_credentials", "line": 340, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out", "timestamp": "2024-10-14T05:45:12.239696+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out", "timestamp": "2024-10-14T05:45:16.182911+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-14T05:45:18.294271+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Authentication failed using Compute Engine authentication due to unavailable metadata server.", "timestamp": "2024-10-14T05:45:18.294398+00:00", "logger": "google.auth._default", "module": "_default", "function": "_get_gce_credentials", "line": 340, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out", "timestamp": "2024-10-14T05:47:35.807522+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out", "timestamp": "2024-10-14T05:47:39.824880+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-14T05:47:41.865911+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Authentication failed using Compute Engine authentication due to unavailable metadata server.", "timestamp": "2024-10-14T05:47:41.866016+00:00", "logger": "google.auth._default", "module": "_default", "function": "_get_gce_credentials", "line": 340, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out", "timestamp": "2024-10-14T05:51:13.879056+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out", "timestamp": "2024-10-14T05:51:17.983483+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-14T05:51:20.153747+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Authentication failed using Compute Engine authentication due to unavailable metadata server.", "timestamp": "2024-10-14T05:51:20.154139+00:00", "logger": "google.auth._default", "module": "_default", "function": "_get_gce_credentials", "line": 340, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised NotFound: 404 models/gpt-3.5-turbo-0125 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..", "timestamp": "2024-10-15T15:43:36.345136+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised NotFound: 404 models/gpt-3.5-turbo-0125 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..", "timestamp": "2024-10-15T15:53:11.456809+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out", "timestamp": "2024-10-15T16:00:36.806499+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out", "timestamp": "2024-10-15T16:00:40.880846+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-15T16:00:43.077053+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Authentication failed using Compute Engine authentication due to unavailable metadata server.", "timestamp": "2024-10-15T16:00:43.077367+00:00", "logger": "google.auth._default", "module": "_default", "function": "_get_gce_credentials", "line": 340, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out", "timestamp": "2024-10-16T10:01:38.736070+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-16T10:01:40.707205+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out", "timestamp": "2024-10-16T10:01:41.621918+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-16T10:01:41.755425+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-16T10:01:42.662482+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out", "timestamp": "2024-10-16T10:01:42.781207+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-16T10:01:43.834112+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Authentication failed using Compute Engine authentication due to unavailable metadata server.", "timestamp": "2024-10-16T10:01:43.835368+00:00", "logger": "google.auth._default", "module": "_default", "function": "_get_gce_credentials", "line": 340, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-16T10:01:44.475353+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Authentication failed using Compute Engine authentication due to unavailable metadata server.", "timestamp": "2024-10-16T10:01:44.476065+00:00", "logger": "google.auth._default", "module": "_default", "function": "_get_gce_credentials", "line": 340, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-16T10:01:44.782091+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Authentication failed using Compute Engine authentication due to unavailable metadata server.", "timestamp": "2024-10-16T10:01:44.783207+00:00", "logger": "google.auth._default", "module": "_default", "function": "_get_gce_credentials", "line": 340, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable", "timestamp": "2024-10-16T11:23:01.477153+00:00", "logger": "google.auth._default", "module": "_default", "function": "default", "line": 685, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T11:23:03.262846+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "No project ID could be determined. Consider running `gcloud config set project` or setting the GOOGLE_CLOUD_PROJECT environment variable", "timestamp": "2024-10-16T11:26:09.855557+00:00", "logger": "google.auth._default", "module": "_default", "function": "default", "line": 685, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T11:26:11.403458+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T22:33:02.552467+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T22:53:27.010281+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T22:55:23.384104+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:00:05.245617+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:03:14.089580+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:14:23.569155+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:17:09.844504+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:19:15.137978+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:24:01.213485+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised NotFound: 404 models/gpt-3.5-turbo-0125 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..", "timestamp": "2024-10-16T23:29:26.698236+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised NotFound: 404 models/gpt-3.5-turbo-0125 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..", "timestamp": "2024-10-16T23:29:43.722117+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised NotFound: 404 models/gpt-3.5-turbo-0125 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..", "timestamp": "2024-10-16T23:31:40.766438+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:36:09.263833+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:39:00.144437+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:40:06.423250+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:41:33.329986+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:44:28.057412+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:47:05.961308+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:48:26.024934+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:49:19.032431+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:50:08.072089+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:50:41.772841+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:51:12.541002+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-16T23:51:50.124629+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-17T01:37:31.763904+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-17T01:38:45.940718+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-17T01:43:32.104909+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised PermissionDenied: 403 Request had insufficient authentication scopes. [reason: \"ACCESS_TOKEN_SCOPE_INSUFFICIENT\"\ndomain: \"googleapis.com\"\nmetadata {\n  key: \"service\"\n  value: \"generativelanguage.googleapis.com\"\n}\nmetadata {\n  key: \"method\"\n  value: \"google.ai.generativelanguage.v1beta.GenerativeService.GenerateContent\"\n}\n].", "timestamp": "2024-10-17T01:44:28.230406+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 Resource has been exhausted (e.g. check quota)..", "timestamp": "2024-10-18T13:20:16.800701+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 Resource has been exhausted (e.g. check quota)..", "timestamp": "2024-10-18T13:21:10.021249+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 Resource has been exhausted (e.g. check quota)..", "timestamp": "2024-10-18T13:22:00.679535+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 Resource has been exhausted (e.g. check quota)..", "timestamp": "2024-10-19T01:36:07.869962+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
