{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out", "timestamp": "2024-10-14T05:42:12.552719+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out", "timestamp": "2024-10-14T05:42:16.543555+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-14T05:42:18.364809+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Authentication failed using Compute Engine authentication due to unavailable metadata server.", "timestamp": "2024-10-14T05:42:18.365613+00:00", "logger": "google.auth._default", "module": "_default", "function": "_get_gce_credentials", "line": 340, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out", "timestamp": "2024-10-14T05:45:12.239696+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out", "timestamp": "2024-10-14T05:45:16.182911+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-14T05:45:18.294271+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Authentication failed using Compute Engine authentication due to unavailable metadata server.", "timestamp": "2024-10-14T05:45:18.294398+00:00", "logger": "google.auth._default", "module": "_default", "function": "_get_gce_credentials", "line": 340, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out", "timestamp": "2024-10-14T05:47:35.807522+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out", "timestamp": "2024-10-14T05:47:39.824880+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-14T05:47:41.865911+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Authentication failed using Compute Engine authentication due to unavailable metadata server.", "timestamp": "2024-10-14T05:47:41.866016+00:00", "logger": "google.auth._default", "module": "_default", "function": "_get_gce_credentials", "line": 340, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out", "timestamp": "2024-10-14T05:51:13.879056+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out", "timestamp": "2024-10-14T05:51:17.983483+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down", "timestamp": "2024-10-14T05:51:20.153747+00:00", "logger": "google.auth.compute_engine._metadata", "module": "_metadata", "function": "ping", "line": 142, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Authentication failed using Compute Engine authentication due to unavailable metadata server.", "timestamp": "2024-10-14T05:51:20.154139+00:00", "logger": "google.auth._default", "module": "_default", "function": "_get_gce_credentials", "line": 340, "thread_name": "ScriptRunner.scriptThread"}
{"level": "WARNING", "message": "Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised NotFound: 404 models/gpt-3.5-turbo-0125 is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..", "timestamp": "2024-10-15T15:43:36.345136+00:00", "logger": "langchain_google_genai.chat_models", "module": "before_sleep", "function": "log_it", "line": 65, "thread_name": "ScriptRunner.scriptThread"}
